import CustomSnackbar from '@/app/components/CustomSnackbar'
import ReduxContainer from '@/app/components/ReduxContainer'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxContainer>
          <CustomSnackbar />
          {children}
        </ReduxContainer>
      </body>
    </html>
  )
}
