
export const data = {
  per_page: 8,
  total: 20,
  data: [
    {
      categoryID: 1,
      id: 1,
      email: 'george.bluth@reqres.in',
      first_name: 'George',
      last_name: 'Bluth',
      avatar: 'https://images.unsplash.com/photo-1696958363946-b58f40cda426',
      des: "Despite multiple complications and her near-death experience Gwen had her best sleep ever on her new bed of nails.We need to rent a room for our party.His confidence would have bee admirable if it wasn't for his stupidity.",
    },
    {
      categoryID: 1,
      id: 2,
      email: 'janet.weaver@reqres.in',
      first_name: 'Janet',
      last_name: 'Weaver',
      avatar:
        'https://plus.unsplash.com/premium_photo-1668447592192-0c1ebadfc1c0',
      des: "Despite multiple complications and her near-death experience Gwen had her best sleep ever on her new bed of nails.We need to rent a room for our party.His confidence would have bee admirable if it wasn't for his stupidity.",
    },
    {
      categoryID: 1,
      id: 3,
      email: 'emma.wong@reqres.in',
      first_name: 'Emma',
      last_name: 'Wong',
      avatar:
        'https://plus.unsplash.com/premium_photo-1695302440940-c954d78d8518',
      des: "Despite multiple complications and her near-death experience Gwen had her best sleep ever on her new bed of nails.We need to rent a room for our party.His confidence would have bee admirable if it wasn't for his stupidity.",
    },
    {
      categoryID: 1,
      id: 4,
      email: 'eve.holt@reqres.in',
      first_name: 'Eve',
      last_name: 'Holt',
      avatar:
        'https://plus.unsplash.com/premium_photo-1688410479265-391776c574a7',
      des: "Despite multiple complications and her near-death experience Gwen had her best sleep ever on her new bed of nails.We need to rent a room for our party.His confidence would have bee admirable if it wasn't for his stupidity.",
    },
    {
      categoryID: 1,
      id: 5,
      email: 'eve.holt@reqres.in',
      first_name: 'Eve',
      last_name: 'Holt',
      avatar:
        'https://plus.unsplash.com/premium_photo-1688410479265-391776c574a7',
      des: "Despite multiple complications and her near-death experience Gwen had her best sleep ever on her new bed of nails.We need to rent a room for our party.His confidence would have bee admirable if it wasn't for his stupidity.",
    },
    {
      categoryID: 2,
      id: 6,
      email: 'george.bluth@reqres.in',
      first_name: 'George',
      last_name: 'Bluth',
      avatar: 'https://images.unsplash.com/photo-1695997592672-61c82527afa9',
      des: "Despite multiple complications and her near-death experience Gwen had her best sleep ever on her new bed of nails.We need to rent a room for our party.His confidence would have bee admirable if it wasn't for his stupidity.",
    },
    {
      categoryID: 2,
      id: 7,
      email: 'george.bluth@reqres.in',
      first_name: 'George',
      last_name: 'Bluth',
      avatar: 'https://images.unsplash.com/photo-1695997592672-61c82527afa9',
      des: "Despite multiple complications and her near-death experience Gwen had her best sleep ever on her new bed of nails.We need to rent a room for our party.His confidence would have bee admirable if it wasn't for his stupidity.",
    },
    {
      categoryID: 2,
      id: 8,
      email: 'george.bluth@reqres.in',
      first_name: 'George',
      last_name: 'Bluth',
      avatar: 'https://images.unsplash.com/photo-1695997592672-61c82527afa9',
      des: "Despite multiple complications and her near-death experience Gwen had her best sleep ever on her new bed of nails.We need to rent a room for our party.His confidence would have bee admirable if it wasn't for his stupidity.",
    },
    {
      categoryID: 2,
      id: 9,
      email: 'eve.holt@reqres.in',
      first_name: 'Eve',
      last_name: 'HoltPageTwo',
      avatar:
        'https://plus.unsplash.com/premium_photo-1688410479265-391776c574a7',
      des: "Despite multiple complications and her near-death experience Gwen had her best sleep ever on her new bed of nails.We need to rent a room for our party.His confidence would have bee admirable if it wasn't for his stupidity.",
    },
    {
      categoryID: 2,
      id: 10,
      email: 'george.bluth@reqres.in',
      first_name: 'George',
      last_name: 'Bluth',
      avatar: 'https://images.unsplash.com/photo-1695997592672-61c82527afa9',
      des: "Despite multiple complications and her near-death experience Gwen had her best sleep ever on her new bed of nails.We need to rent a room for our party.His confidence would have bee admirable if it wasn't for his stupidity.",
    },
    {
      categoryID: 3,
      id: 11,
      email: 'george.bluth@reqres.in',
      first_name: 'George',
      last_name: 'Bluth',
      avatar: 'https://images.unsplash.com/photo-1695997592672-61c82527afa9',
      des: "Despite multiple complications and her near-death experience Gwen had her best sleep ever on her new bed of nails.We need to rent a room for our party.His confidence would have bee admirable if it wasn't for his stupidity.",
    },
    {
      categoryID: 3,
      id: 12,
      email: 'janet.weaver@reqres.in',
      first_name: 'Janet',
      last_name: 'Weaver',
      avatar:
        'https://plus.unsplash.com/premium_photo-1668447592192-0c1ebadfc1c0',
      des: "Despite multiple complications and her near-death experience Gwen had her best sleep ever on her new bed of nails.We need to rent a room for our party.His confidence would have bee admirable if it wasn't for his stupidity.",
    },
    {
      categoryID: 3,
      id: 13,
      email: 'emma.wong@reqres.in',
      first_name: 'Emma',
      last_name: 'Wong',
      avatar:
        'https://plus.unsplash.com/premium_photo-1695302440940-c954d78d8518',
      des: "Despite multiple complications and her near-death experience Gwen had her best sleep ever on her new bed of nails.We need to rent a room for our party.His confidence would have bee admirable if it wasn't for his stupidity.",
    },
    {
      categoryID: 3,
      id: 14,
      email: 'eve.holt@reqres.in',
      first_name: 'Eve',
      last_name: 'Holt',
      avatar:
        'https://plus.unsplash.com/premium_photo-1688410479265-391776c574a7',
      des: "Despite multiple complications and her near-death experience Gwen had her best sleep ever on her new bed of nails.We need to rent a room for our party.His confidence would have bee admirable if it wasn't for his stupidity.",
    },
    {
      categoryID: 3,
      id: 15,
      email: 'eve.holt@reqres.in',
      first_name: 'Eve',
      last_name: 'Holt',
      avatar:
        'https://plus.unsplash.com/premium_photo-1688410479265-391776c574a7',
      des: "Despite multiple complications and her near-death experience Gwen had her best sleep ever on her new bed of nails.We need to rent a room for our party.His confidence would have bee admirable if it wasn't for his stupidity.",
    },
    {
      categoryID: 4,
      id: 16,
      email: 'george.bluth@reqres.in',
      first_name: 'George',
      last_name: 'Bluth',
      avatar: 'https://images.unsplash.com/photo-1695997592672-61c82527afa9',
      des: "Despite multiple complications and her near-death experience Gwen had her best sleep ever on her new bed of nails.We need to rent a room for our party.His confidence would have bee admirable if it wasn't for his stupidity.",
    },
    {
      categoryID: 4,
      id: 17,
      email: 'george.bluth@reqres.in',
      first_name: 'George',
      last_name: 'BluthLast',
      avatar: 'https://images.unsplash.com/photo-1695997592672-61c82527afa9',
      des: "Despite multiple complications and her near-death experience Gwen had her best sleep ever on her new bed of nails.We need to rent a room for our party.His confidence would have bee admirable if it wasn't for his stupidity.",
    },
    {
      categoryID: 4,
      id: 18,
      email: 'george.bluth@reqres.in',
      first_name: 'George',
      last_name: 'Bluth',
      avatar: 'https://images.unsplash.com/photo-1695997592672-61c82527afa9',
      des: "Despite multiple complications and her near-death experience Gwen had her best sleep ever on her new bed of nails.We need to rent a room for our party.His confidence would have bee admirable if it wasn't for his stupidity.",
    },
    {
      categoryID: 4,
      id: 19,
      email: 'eve.holt@reqres.in',
      first_name: 'Eve',
      last_name: 'Holt',
      avatar:
        'https://plus.unsplash.com/premium_photo-1688410479265-391776c574a7',
      des: "Despite multiple complications and her near-death experience Gwen had her best sleep ever on her new bed of nails.We need to rent a room for our party.His confidence would have bee admirable if it wasn't for his stupidity.",
    },
    {
      categoryID: 4,
      id: 20,
      email: 'george.bluth@reqres.in',
      first_name: 'George',
      last_name: 'Bluth',
      avatar: 'https://images.unsplash.com/photo-1695997592672-61c82527afa9',
      des: "Despite multiple complications and her near-death experience Gwen had her best sleep ever on her new bed of nails.We need to rent a room for our party.His confidence would have bee admirable if it wasn't for his stupidity.",
    },
    {
      categoryID: 5,
      id: 21,
      email: 'george.bluth@reqres.in',
      first_name: 'George',
      last_name: 'Bluth',
      avatar: 'https://images.unsplash.com/photo-1695997592672-61c82527afa9',
      des: "Despite multiple complications and her near-death experience Gwen had her best sleep ever on her new bed of nails.We need to rent a room for our party.His confidence would have bee admirable if it wasn't for his stupidity.",
    },
    {
      categoryID: 5,
      id: 22,
      email: 'george.bluth@reqres.in',
      first_name: 'George',
      last_name: 'Bluth',
      avatar: 'https://images.unsplash.com/photo-1695997592672-61c82527afa9',
      des: "Despite multiple complications and her near-death experience Gwen had her best sleep ever on her new bed of nails.We need to rent a room for our party.His confidence would have bee admirable if it wasn't for his stupidity.",
    },
    {
      categoryID: 5,
      id: 23,
      email: 'george.bluth@reqres.in',
      first_name: 'George',
      last_name: 'Bluth',
      avatar: 'https://images.unsplash.com/photo-1695997592672-61c82527afa9',
      des: "Despite multiple complications and her near-death experience Gwen had her best sleep ever on her new bed of nails.We need to rent a room for our party.His confidence would have bee admirable if it wasn't for his stupidity.",
    },
    {
      categoryID: 5,
      id: 24,
      email: 'george.bluth@reqres.in',
      first_name: 'George',
      last_name: 'Bluth',
      avatar: 'https://images.unsplash.com/photo-1695997592672-61c82527afa9',
      des: "Despite multiple complications and her near-death experience Gwen had her best sleep ever on her new bed of nails.We need to rent a room for our party.His confidence would have bee admirable if it wasn't for his stupidity.",
    },
    {
      categoryID: 5,
      id: 25,
      email: 'george.bluth@reqres.in',
      first_name: 'George',
      last_name: 'Bluth',
      avatar: 'https://images.unsplash.com/photo-1695997592672-61c82527afa9',
      des: "Despite multiple complications and her near-death experience Gwen had her best sleep ever on her new bed of nails.We need to rent a room for our party.His confidence would have bee admirable if it wasn't for his stupidity.",
    },
  ],
}

export const GetDataById = (detailID) => {
   return data.data.find(vl => vl.id == detailID)
  }
  